apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-java-web-application
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: sample-java-web-application
  endpoints:
  - port: web
    interval: 30s
