apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-java-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-java-webapp
  template:
    metadata:
      labels:
        app: sample-java-webapp
    spec:
      containers:
      - name: sample-java-webapp
        image: venkateshdocker1/sample-java-webapp:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-java-webapp-service
spec:
  selector:
    app: sample-java-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

